accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("signup/", views.signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('receipts/', include("receipts.urls")),
    path('accounts/', include('accounts.urls')),
    path("", RedirectView.as_view(url=reverse_lazy("home")))
]

   #path('accounts/', include("accounts.urls")),
   #path('accounts/', include('django.contrib.auth.urls')),

receipts/urls.py
from django.urls import path

from receipts.views import ReceiptAccountCreateView, ReceiptAccountListView, ReceiptCategoryCreateView, ReceiptCategoryListView, ReceiptCreateView, ReceiptListView

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="receipt_new"),
    path("accounts/", ReceiptAccountListView.as_view(), name="receipt_account_list"),
    path("accounts/create/", ReceiptAccountCreateView.as_view(), name="receipt_account_new"),
    path("categories/", ReceiptCategoryListView.as_view(), name="receipt_category_list"),
    path("categories/create/", ReceiptCategoryCreateView.as_view(), name="receipt_category_new"),
]

accounts/models.py
from django.conf import settings
from django.db import models

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.

#class User(models.Model):
    #username = models.ForeignKey(USER_MODEL, related_name="account", on_delete=models.CASCADE)
    #password = models.ForeignKey(USER_MODEL, related_name="account", on_delete=models.CASCADE)

receipts/models.py
from tkinter import CASCADE
from django.db import models

from accounts.models import USER_MODEL

# Create your models here.

class Account(models.Model):
    name = models.CharField(max_length = 100, null=True)
    number = models.CharField(max_length = 20, null=True)
    owner = models.ForeignKey(USER_MODEL, related_name="accounts", on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

class ExpenseCategory(models.Model):
    name = models.CharField(max_length = 50, null=True)
    owner = models.ForeignKey(USER_MODEL, related_name="categories", on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

class Receipt(models.Model):
    vendor = models.CharField(max_length = 200, null=True)
    total = models.DecimalField(decimal_places=3, max_digits=10, null=True)
    tax = models.DecimalField(decimal_places=3, max_digits=10, null=True)
    date = models.DateTimeField(null=True)
    category = models.ForeignKey("ExpenseCategory", related_name="receipts", on_delete=models.CASCADE, null=True, blank=True)
    account = models.ForeignKey(Account, related_name="receipts", on_delete=models.CASCADE, blank=True, null=True)
    purchaser = models.ForeignKey(USER_MODEL, related_name="receipts", on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.vendor

#null = True is database side of data.. blank = true is form side of data

accounts/views.py
from django.shortcuts import redirect, render

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required

# Create your views here.

#class AccountCreateView(LoginRequiredMixin, CreateView):
    #pass


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

    #function signup(request)
    #if the request method is "POST", then
        #form = UserCreationForm(request.POST)
        #if the form is valid, then
            #username = the "username" value from the request.POST dictionary
            #password = the "password1" value from the request.POST dictionary
            #user = create a new user using username and password
            #save the user object
            #login the user with the request and user object
            #return a redirect to the "home" path
    #otherwise,
        #form = UserCreationForm(request.POST)
   # context = dictionary with key "form" and value form
    #return render with request, "registration/signup.html", and the context



    #context = {}
    #form = UserCreationForm(request.POST or None)
    #if request.method == "POST":
        #if form.is_valid():
            #user = form.save()
            #login(request,user)
            #return render(request,'accounts/login.html')
    #context['form']=form
    #return render(request,'accounts/sign_up.html',context)

receipts/views.py
from django.shortcuts import redirect, render

from receipts.models import Account, ExpenseCategory, Receipt
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from django.contrib.auth.mixins import LoginRequiredMixin


class ReceiptListView(ListView):
    model = Receipt
    template_name = "receipts/list.html"


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/new.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    success_url = reverse_lazy("home")

    #def get_success_url(self):
        #return reverse_lazy("home", args=[self.object.id])

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("home")

        #form.instance.user = self.request.user
        #return super().form_valid(form)

        #i think i will have to change the .author here?


class ReceiptAccountListView(ListView):
    model = Account
    template_name = "accounts/list.html"


class ReceiptAccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/new.html"
    fields = ["name", "number"]
    success_url = reverse_lazy("receipt_account_list")

    def form_valid(self, form):
        item = form.save(commit=False)
        # this returns an object that hasn't yet been saved to the database
        item.owner = self.request.user
        item.save()
        return redirect("receipt_account_list")


class ReceiptCategoryListView(ListView):
    model = ExpenseCategory
    template_name = "categories/list.html"


class ReceiptCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "categories/new.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        # this returns an object that hasn't yet been saved to the database
        item.purchaser = self.request.user
        item.save()
        return redirect("receipt_account_list")

receipts/templates/accounts/list.html
{% extends 'base.html' %} {% block content %}
  <main>
    <header>
     <h1>Accounts</h1>
    </header>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for item in account_list %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.number }}</td>
                <td>{{ item.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </main>
    {% endblock content %}

receipts/templates/accounts/new.html
{% extends 'base.html' %} {% block content %}
  <main>
    <header>
     <h1>Create Account</h1>
    </header>
    <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
</main>
{% endblock content %}

receipts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Expenses</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
  </head>

  <body>
      <nav>
        {% if request.user.is_authenticated %}
          <a href="{% url 'home' %}">Receipts</a>
          <a href="{% url 'receipt_new' %}">Create receipt</a>
          <a href="{% url 'receipt_account_list' %}">Accounts</a>
          <a href="{% url 'receipt_account_new' %}">Create account</a>
          <a href="{% url 'receipt_category_list' %}">Categories</a>
          <a href="{% url 'receipt_category_new' %}">Create category</a>
          <a href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a href="{% url 'signup' %}">Sign Up</a>
          <a href="{% url 'login' %}">Login</a>
          {% endif %}
      </nav>
    {% block content %} {% endblock content %}
  </body>
</html>

receipts/templates/categories/list.html
{% extends 'base.html' %} {% block content %}
    <main>
    <header>
     <h1>Expense Categories</h1>
    </header>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number of receipts</th>
            </tr>
        </thead>
        <tbody>
            {% comment %} INSERT FOR LOOP CONTAINING DETAILS {% endcomment %}
        </tbody>
        {% for item in expensecategory_list %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.receipts.all|length }}</td>
        </tr>
        {% endfor %}

    </table>
    </main>
    {% endblock content %}

receipts/templates/categories/new.html
{% extends 'base.html' %} {% block content %}
<main>
    <header>
     <h1>Create Category</h1>
    </header>
    <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
</main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %} {% block content %}
    <main>
    <header>
     <h1>Receipts</h1>
    </header>
    <table>
        <thead>
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </tr>
        </thead>
        <tbody>
            {% for item in receipt_list %}
            <tr>
                <td>{{ item.vendor }}</td>
                <td>{{ item.total }}</td>
                <td>{{ item.tax }}</td>
                <td>{{ item.date|date:"m-d-Y" }}</td>
                <td>{{ item.category.name }}</td>
                <td>{{ item.account.name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </main>
    {% endblock content %}

receipts/templates/receipts/new.html
{% extends 'base.html' %} {% block content %}
  <main>
    <header>
    </header>
    <form method="post">
        <h1>Create Receipt</h1>
        {% csrf_token %} {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
  </body>
</main>
{% endblock content %}